version: '3.8'

services:
  db:
    image: postgres:15
    container_name: training_postgres
    environment:
      POSTGRES_DB: training_app
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5678:5432"

  app:
    build: .
    container_name: training_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/training_app
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_USER_NAME: name
      SPRING_SECURITY_USER_PASSWORD: password
      SPRINGDOC_API_DOCS_ENABLED: true
      SPRINGDOC_SWAGGER_UI_ENABLED: true
    ports:
      - "8080:8080"

volumes:
  pgdata:
